name: utang_core
description: "Catatan Utang"
publish_to: "none"
version: 1.1.2

environment:
  sdk: ^3.5.3

dependencies:
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  google_mobile_ads: 5.3.1
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  shared_preferences_foundation: ^2.5.4
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0
  json_serializable: ^6.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_utang_core.png" # Sesuaikan dengan lokasi logo
  adaptive_icon_background: "#ffffff" # (Opsional) untuk Android Adaptive Icons
  adaptive_icon_foreground: "assets/logo_utang_core.png"

flutter:
  uses-material-design: true
  assets:
    - .env
